/** @type {import('tailwindcss').Config} */
// The design system is the source of truth. Every value here points at a CSS
// custom property defined in src/styles/tokens/*.css — the token names are kept
// 1:1 with designs/tokens/*. Do not introduce colours, radii or type sizes that
// are not already a token.
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    // Replace, not extend: the palette is closed.
    colors: {
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",

      // base — warm paper neutrals
      paper: {
        100: "var(--paper-100)",
        200: "var(--paper-200)",
        300: "var(--paper-300)",
        400: "var(--paper-400)",
        500: "var(--paper-500)",
        600: "var(--paper-600)",
        700: "var(--paper-700)",
      },
      line: {
        100: "var(--line-100)",
        200: "var(--line-200)",
        300: "var(--line-300)",
        400: "var(--line-400)",
        500: "var(--line-500)",
      },
      ink: {
        100: "var(--ink-100)",
        150: "var(--ink-150)",
        200: "var(--ink-200)",
        300: "var(--ink-300)",
        400: "var(--ink-400)",
        500: "var(--ink-500)",
        600: "var(--ink-600)",
        700: "var(--ink-700)",
        800: "var(--ink-800)",
        900: "var(--ink-900)",
      },
      teal: {
        50: "var(--teal-050)",
        75: "var(--teal-075)",
        100: "var(--teal-100)",
        200: "var(--teal-200)",
        600: "var(--teal-600)",
        700: "var(--teal-700)",
      },
      terracotta: {
        100: "var(--terracotta-100)",
        200: "var(--terracotta-200)",
        600: "var(--terracotta-600)",
        800: "var(--terracotta-800)",
      },
      ochre: {
        100: "var(--ochre-100)",
        200: "var(--ochre-200)",
        600: "var(--ochre-600)",
        700: "var(--ochre-700)",
      },
      project: {
        1: "var(--project-1)",
        2: "var(--project-2)",
        3: "var(--project-3)",
        4: "var(--project-4)",
        5: "var(--project-5)",
        none: "var(--project-none)",
      },
    },
    // Semantic aliases — the names the components actually reach for.
    textColor: ({ theme }) => ({
      ...theme("colors"),
      primary: "var(--text-primary)",
      body: "var(--text-body)",
      secondary: "var(--text-secondary)",
      muted: "var(--text-muted)",
      label: "var(--text-label)",
      "on-dark": "var(--text-on-dark)",
      "on-dark-muted": "var(--text-on-dark-muted)",
      link: "var(--text-link)",
      "link-hover": "var(--text-link-hover)",
      accent: "var(--accent-text)",
    }),
    backgroundColor: ({ theme }) => ({
      ...theme("colors"),
      desk: "var(--bg-desk)",
      app: "var(--surface-app)",
      sidebar: "var(--surface-sidebar)",
      panel: "var(--surface-panel)",
      card: "var(--surface-card)",
      sunken: "var(--surface-sunken)",
      "row-hover": "var(--surface-row-hover)",
      "row-selected": "var(--surface-row-selected)",
      "row-selected-hover": "var(--surface-row-selected-hover)",
      toolbar: "var(--surface-toolbar)",
      "toolbar-control": "var(--surface-toolbar-control)",
      accent: "var(--accent)",
      "accent-hover": "var(--accent-hover)",
      "accent-tint": "var(--accent-tint)",
    }),
    borderColor: ({ theme }) => ({
      ...theme("colors"),
      DEFAULT: "var(--border-default)",
      window: "var(--border-window)",
      subtle: "var(--border-subtle)",
      dashed: "var(--border-dashed)",
      hover: "var(--border-hover)",
      "accent-tint": "var(--accent-tint-border)",
    }),
    borderRadius: {
      none: "0",
      sm: "var(--radius-sm)",
      DEFAULT: "var(--radius)",
      lg: "var(--radius)",
      window: "var(--radius-window)",
      round: "var(--radius-round)",
      full: "var(--radius-round)",
    },
    fontFamily: {
      sans: "var(--font-sans)",
    },
    fontSize: {
      "2xs": "var(--text-2xs)",
      xs: "var(--text-xs)",
      sm: "var(--text-sm)",
      base: "var(--text-base)",
      md: "var(--text-md)",
      lg: "var(--text-lg)",
      xl: "var(--text-xl)",
      "2xl": "var(--text-2xl)",
      "3xl": "var(--text-3xl)",
    },
    fontWeight: {
      regular: "var(--weight-regular)",
      medium: "var(--weight-medium)",
      semibold: "var(--weight-semibold)",
      bold: "var(--weight-bold)",
      black: "var(--weight-black)",
    },
    lineHeight: {
      tight: "var(--leading-tight)",
      snug: "var(--leading-snug)",
      normal: "var(--leading-normal)",
    },
    letterSpacing: {
      title: "var(--tracking-title)",
      label: "var(--tracking-label)",
    },
    boxShadow: {
      none: "none",
      card: "var(--shadow-card)",
      raised: "var(--shadow-raised)",
      window: "var(--shadow-window)",
      lifted: "var(--shadow-lifted)",
      popover: "var(--shadow-popover)",
      dialog: "var(--shadow-dialog)",
    },
    extend: {
      spacing: {
        sidebar: "var(--sidebar-w)",
        "project-col": "var(--project-col-w)",
        "detail-panel": "var(--detail-panel-w)",
        gutter: "var(--gutter)",
        "1t": "var(--space-1)",
        "2t": "var(--space-2)",
        "3t": "var(--space-3)",
        "4t": "var(--space-4)",
        "5t": "var(--space-5)",
        "6t": "var(--space-6)",
        "7t": "var(--space-7)",
        "8t": "var(--space-8)",
        "9t": "var(--space-9)",
        "10t": "var(--space-10)",
        "11t": "var(--space-11)",
        "12t": "var(--space-12)",
      },
      transitionTimingFunction: {
        ds: "ease",
      },
      transitionDuration: {
        ds: "120ms",
      },
    },
  },
  plugins: [],
};
